export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';


export const SET_LOADING = 'SET_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const COMPLETE_SETUP = 'COMPLETE_SETUP';


export const CLEAR_REPOSITORIES = 'CLEAR_REPOSITORIES';
export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const SAVE_REPOSITORIES = 'SAVE_REPOSITORIES';
